# Generated by Django 5.0.2 on 2024-02-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_tasklist_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='manager',
        ),
    ]
