# Generated by Django 5.0.2 on 2024-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_remove_tasklist_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
